package com.example.needflix

object DrakorCast {
    public val castPhoto = mapOf(
        "Cha Soo-hyang" to R.drawable.cho_soo_yang,
        "Dayoung" to R.drawable.dayoung,
        "Gong Yoo" to R.drawable.gong_yoo,
        "Hwang In-youp" to R.drawable.hwang_in_youp,
        "Hyun Bin" to R.drawable.hyun_bin,
        "Jeon Mi-do" to R.drawable.jeon_mi_do,
        "Jeon Yeo-been" to R.drawable.jeon_yeo_been,
        "Jin Goo" to R.drawable.jin_goo,
        "Jo Jung-suk" to R.drawable.jo_jung_suk,
        "Jung Da Eun" to R.drawable.jung_da_eun,
        "Jung Kyung-ho" to R.drawable.jung_kyung_ho,
        "Jung So-min" to R.drawable.jung_so_min,
        "Kang Ki-young" to R.drawable.kang_ki_young,
        "Kim Go-eun" to R.drawable.kim_go_eun,
        "Kim Ha-neul" to R.drawable.kim_ha_neul,
        "Kim Hee-jung" to R.drawable.kim_hee_jung,
        "Kim Ji-won" to R.drawable.kim_ji_won,
        "Kim Min-seok" to R.drawable.kim_min_seok,
        "Kim So-hyun" to R.drawable.kim_so_hyun,
        "Kwak Dong-yeon" to R.drawable.kwak_dong_yeon,
        "Kwon Yul" to R.drawable.kwon_yul,
        "Lee Da-wit" to R.drawable.lee_da_wit,
        "Lee Dohyun" to R.drawable.lee_dohyun,
        "Lee Dong-wook" to R.drawable.lee_dong_wook,
        "Lee Jae-wook" to R.drawable.lee_jae_wook,
        "Lee Ruby" to R.drawable.lee_ruby,
        "Lee Tae-hwan" to R.drawable.lee_tae_hwan,
        "Na Cheol" to R.drawable.na_cheol,
        "Nam Joo-hyuk" to R.drawable.nam_joo_hyuk,
        "Ok Taec-yeon" to R.drawable.ok_taec_yeon,
        "Park Chan-yeol" to R.drawable.park_chan_yeol,
        "Park Hoon" to R.drawable.park_hoon,
        "Park Ji-hoon" to R.drawable.park_ji_hoon,
        "Park Min-young" to R.drawable.park_min_young,
        "Park Seo-joon" to R.drawable.park_seo_joon,
        "Park Shin-hye" to R.drawable.park_shin_hye,
        "Roh Jeong-eui" to R.drawable.roh_jeong_eui,
        "Shin Hyun Bin" to R.drawable.shin_hyun_bin,
        "Song Hye-kyo" to R.drawable.song_hye_kyo,
        "Song Joong-ki" to R.drawable.song_joong_ki,
        "Wi Ha-joon" to R.drawable.wi_ha_joon,
        "Yoo In-na" to R.drawable.yoo_in_na,
        "Yoo Yeon-seok" to R.drawable.yoo_yeon_seok,
        "Yook Seung-jae" to R.drawable.yook_seung_jae,
        "Younghoon" to R.drawable.younghoon
    )
}